### ISSUE TITLE
Traceback in send_to_datadog.py for Firefox Nightly

### ISSUE THREAD

**Issue by stephendonner** [mozilla/wpt-api#122]
Hey @davehunt!

I added a ```+``` char in-between Chrome Canary and Firefox Nightly, over in https://github.com/mozilla/wpt-api/commit/d31c40cd6941c8e82915f461fd594b6940b28940, which seems to have fixed https://github.com/mozilla/wpt-api/issues/119

```

11/06/18 18:15:02 | US East - Linux (N. Virginia) - Firefox+Nightly - Cable | netflix.fx.nightly | https://www.netflix.com
```

But now we're seeing the following error:

```
02:15:52 [netflix] Running shell script
02:15:53 + python ./send_to_datadog.py wpt.json
02:15:53 netflix.fx.release
02:15:53 - TTFB: 308
02:15:53 - render: 800
02:15:53 - firstPaint: 685
02:15:53 - timeToDOMContentFlushed: 1541556912883
02:15:53 - SpeedIndex: 850
02:15:53 - bytesInDoc: 1167839
02:15:53 - visualComplete: 1600
02:15:53 - requestsFull: 63
02:15:53 netflix.fx.nightly
02:15:53 Traceback (most recent call last):
02:15:53   File "./send_to_datadog.py", line 44, in <module>
02:15:53     main(*sys.argv[1:])
02:15:53   File "./send_to_datadog.py", line 35, in main
02:15:53     value = test["data"]["median"]["firstView"][metric]
02:15:53 TypeError: list indices must be integers or slices, not str
[Pipeline] }
02:15:53 $ docker stop --time=1 424dab6fc8275e431e75bd92bf914352f57489968561644cfe7f11c9fb992c6b
02:15:54 $ docker rm -f 424dab6fc8275e431e75bd92bf914352f57489968561644cfe7f11c9fb992c6b
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```
https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/wpt/job/netflix/5/console

**Comment by davehunt** [comment]
Instead of a "+" it looks like we needed "%20" so the string is URL encoded. This error suggests there was no data for label "netflix.fx.nightly", though the message could be improved. As I believe I've fixed this in https://github.com/mozilla/wpt-api/commit/c9174a3623707b16833eeaa64cb9c88f0793ecc9 I'm going to close it. We can add better error handling later.
